server:
  port: 9090

global:
  result:
    handler:
      print: true

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

logging:
  level:
    cm.gingo: DEBUG